# Generated by Django 4.2.30 on 2026-09-07 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoreCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_index", models.PositiveIntegerField()),
                ("done", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="chores.chore",
                    ),
                ),
            ],
            options={
                "ordering": ["week_index", "chore__order"],
            },
        ),
        migrations.AddConstraint(
            model_name="chorecompletion",
            constraint=models.UniqueConstraint(
                fields=("chore", "week_index"), name="unique_chore_week_completion"
            ),
        ),
    ]
